### ISSUE TITLE
2.1 format

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#1]
Just as a reminder
https://github.com/CityScope/CS_CityIO_Backend/issues/63

**Comment by RELNO** [comment]
done with https://github.com/CityScope/CS_Scanner_Python/commit/69654441e9aa89ed1954107e3e6e108599daf598.

**Comment by RELNO** [comment]
see https://cityio.media.mit.edu/api/table/grasbrook

**Comment by agrignard** [comment]
Is it the right value? it seems that there is less value in the grid?

`````
"nrows":24,"ncols":72
`````
24x72=1728 and there is 576 values 
https://cityio.media.mit.edu/api/table/grasbrook

**Comment by RELNO** [comment]
I get 1728 [or what ever nocl*crows has], check again please.

**Comment by agrignard** [comment]
my bad 
yep it's ok
