### ISSUE TITLE
scanning_rectangles escape video extents when using cell_gap

### ISSUE THREAD

**Issue by dunland** [CityScope/CS_Scanner_Python#10]
When defining a `cell_gap` for the grid in the `settings.json`, the scan coordinates fall out of the video margins. That is, the rectangles are placed nicely with some spacing in between, but the outermost ones disappear beyond the frame of the video.
Anything I can do to avoid this? It's quite hard to wrap my mind around the Code of the image buildup in `cityscopy.py`.

edit: one workaround seems to **not** center the grid anymore by multiplying `grid_x_offset` and `grid_y_offset` by 0, and reducing the `x_ratio` and `y_ratio` by multiplying it with, say, 0.9.

**Comment by RELNO** [comment]
@dunland thanks, good catch. THe `cell_gap` prop is an old feature made specifically for one deployment of CityScope that used a physical plastic grid in between the LEGOs. We don't use these grids anymore, and so this feature is obsolete. Indeed, if you'd like to use it, the prop won't handle well the gaps. 
If you have a better solution, I'd love for you to PR. Thanks.

**Comment by RELNO** [comment]
@dunland I went ahead and removed it from the master in #11. Closing for now.

**Comment by dunland** [comment]
So I tried to fix this with a couple of lines. I hope I didn't miss anything.. have a look at my pull request, if you like!
