### ISSUE TITLE
Initial Camera Keystone settings

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#17]
By running the script as it is I have the feeling that there is already a keystone applied to the camera which produce this rendering

![Screen Shot 2022-01-21 at 1 21 53 PM](https://user-images.githubusercontent.com/3928502/150526757-49e858f2-d8b2-4a78-af62-2a5fa05d24e5.png)

where as my camera is actually looking at this (without any keystoning)
![Screen Shot 2022-01-21 at 1 23 50 PM](https://user-images.githubusercontent.com/3928502/150526797-b1833b8e-bcb2-468c-9e2b-25ca94b0a33b.png)

What about having by default az non keystone camera and the the user will calibrate it and set it own settings?

**Comment by RELNO** [comment]
in `run.py` simply uncomment the ketstone method

```
    CITYSCOPY_SETTINGS_PATH = "settings/cityscopy.json"
    # init cityscopy class
    cityscopy = Cityscopy(CITYSCOPY_SETTINGS_PATH)
    # run CityScopy main methods
    # keystone the scanned area
    ---> cityscopy.keystone()
    # scan the grid and send to cityIO
    cityscopy.scan()
    # start local UDP comms
    # # cityscopy.udp_listener()
```

**Comment by agrignard** [comment]
Thank you @RELNO my bad I didn't get the concept of commenting the part of the code. the keystone is now looking right
