### ISSUE TITLE
Is there any specs for the webcam

### ISSUE THREAD

**Issue by SRobles97** [CityScope/CS_Scanner_Python#19]
I'm student trying out the scanner, and I'm having trouble and I don't know if it's because of shadow o camera resolution

![image](https://user-images.githubusercontent.com/37591168/211886270-1d5743bc-9ae1-4189-8451-15b6e139295a.png)

I printed a document with some basic coding from a test project in cityio

![image2](https://user-images.githubusercontent.com/37591168/211886963-22787b89-accf-46b2-b45f-53ed80b4cb0b.jpg)

**Comment by RELNO** [comment]
Looks like the scanning works quite well for you. Are you using `test` as your cityscopeJS endpoint? if so you can check what is being sent at https://cityio.media.mit.edu/api/table/test/cityscopy. You do also need to update your local setting file [ https://github.com/CityScope/CS_CityScoPy/blob/cityio-types/cityscopy/settings/test.json ] so that each pattern is equal to the what you printed, i.e -  this type will be detected by the scanner each time a fully white 4x4 cell is present:

<img width="320" alt="Screenshot 2023-01-11 at 1 38 08 PM" src="https://user-images.githubusercontent.com/14296774/211890260-b4f6e495-5dac-4192-8259-1eb139a5e0ac.png">

**Comment by SRobles97** [comment]
So this is my test.json
```json
{
  "CITYIO_API_URL": "https://cityio.media.mit.edu/api/table/",
  "CITYSCOPE_PRJ_NAME": "test",
  "TOGGLE_SEND_TO_CITYIO": true,
  "nrows": 4,
  "ncols": 3,
  "cell_gap": 10,
  "camId": 0,
  "interval": 2000,
  "gui": true,
  "mirror_cam": true,
  "keystone_points_list": "406.0  69.0  261.0  74.0  411.0  243.0  261.0  248.0",
  "types": {
    "Campus": {
      "name": "Campus",
      "color": [
        171,
        143,
        57
      ],
      "height": [
        0,
        15,
        30
      ],
      "cityscopy_id": 0,
      "cityscopy_pattern": "0000000000000000"
    },
    "Office": {
      "name": "Office",
      "color": [
        36,
        130,
        198
      ],
      "height": [
        0,
        50,
        100
      ],
      "cityscopy_id": 1,
      "cityscopy_pattern": "0000000000000001"
    },
    "Park": {
      "name": "Park",
      "color": [
        126,
        179,
        70
      ],
      "height": [
        0,
        0,
        0
      ],
      "cityscopy_id": 2,
      "cityscopy_pattern": "0000000000000010"
    },
    "Residential": {
      "name": "Residential",
      "color": [
        185,
        126,
        24
      ],
      "height": [
        0,
        50,
        100
      ],
      "cityscopy_id": 3,
      "cityscopy_pattern": "0000000000000011"
    }
  }
}
```

I believe the patterns are correct but in https://cityio.media.mit.edu/api/table/test/cityscopy
there's the next output

```
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
```

**Comment by RELNO** [comment]
good find - fixed the bug in 8b303d2. Please pull and test again.
correction - your updated grid will not show in \cityscopy but otherwise in \GEOGRIDDATA

Here's a quick scan (i don't have a grid, just whatever my webcam sees..)
<img width="676" alt="Screenshot 2023-01-11 at 2 29 33 PM" src="https://user-images.githubusercontent.com/14296774/211900153-1fd04379-2f97-4113-9b2b-ac224bd44cbb.png">

**Comment by RELNO** [comment]
correction - your updated grid will not show in `\cityscopy` but otherwise in `\GEOGRIDDATA`

**Comment by SRobles97** [comment]
The scanned grid is send to cityio but is supposed to scan something like
[Park Residential Park
Office Campus Park
Campus Park Residential
Office Residential Campus]

and my scan looks like this
![image](https://user-images.githubusercontent.com/37591168/211903161-eb6f055c-5a2f-4258-a80c-dbcf8649deee.png)

and the output in geogriddata
```json
[
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  },
  {
    "cityscopy_id": -1,
    "color": [
      0,
      0,
      0
    ],
    "height": [
      0,
      0,
      0
    ],
    "name": "Err"
  }
]
```

**Comment by RELNO** [comment]
One quick test for you is to see what happens if scanning something random and if that triggers any of your tags. Another is to check the mirror cam flag in the settings file, to see if your tags are mirrored

**Comment by SRobles97** [comment]
If i put my hand in front of the camera the scan shows some Campus tags, I'll check the mirror cam flag now

But even if mirrowed the Campus tag should be scanned I think because the patterns are all zeroes

**Comment by SRobles97** [comment]
> good find - fixed the bug in [8b303d2](https://github.com/CityScope/CS_CityScoPy/commit/8b303d2c4dc669ee9c35fff31ab9dadd074e87ca). Please pull and test again. correction - your updated grid will not show in \cityscopy but otherwise in \GEOGRIDDATA
> 
> Here's a quick scan (i don't have a grid, just whatever my webcam sees..) <img alt="Screenshot 2023-01-11 at 2 29 33 PM" width="676" src="https://user-images.githubusercontent.com/14296774/211900153-1fd04379-2f97-4113-9b2b-ac224bd44cbb.png">

So if scan something random my scan shows the same as in the quote
If I scan the sheet I printed shows all Errors

I tried the mirror cam flag and it's the same result

**Comment by RELNO** [comment]
can you do a test with a simple grid of 2x2 and only two types of all white and all black? this might be easier to debug. 
You dont need to print a real grid for that, just let the camera see half black and half white paper/image.

**Comment by SRobles97** [comment]
Does the border of grids affect the scan?
I'm thinking I should print the same sheet as above but without the borders.
Something like this for example
![image](https://user-images.githubusercontent.com/37591168/211921022-a958dd85-9f78-4758-9e5f-0b6755755f8b.png)

**Comment by RELNO** [comment]
@SRobles97 I believe you should be all set now. Had a couple of bugs and on my end it works well now. LMK.

**Comment by SRobles97** [comment]
This is my scan
![image](https://user-images.githubusercontent.com/37591168/211940826-2e584eab-5918-461f-8deb-b23faa933800.png)
In geogriddata I have the same output as above

If I scan something random I got this
![image](https://user-images.githubusercontent.com/37591168/211940964-10b1c038-3273-4c51-998d-2760b8e45694.png)

If I scan a white sheet
![image](https://user-images.githubusercontent.com/37591168/211941173-9fd86063-30dd-42e6-a04d-b91357f9b7a1.png)

**Comment by RELNO** [comment]
please pull latest commit and let me know - the tags show well on my end

**Comment by SRobles97** [comment]
at least for me it's the same result
![image](https://user-images.githubusercontent.com/37591168/212213540-53fee535-b537-4f14-b11c-cd89b9a6156a.png)

**Comment by SRobles97** [comment]
![imagen](https://user-images.githubusercontent.com/37591168/212332067-116fb796-9556-4344-88ec-bc17bed935f0.png)
Nevermind my previous answer.
I changed the patterns like 0 = black and 1 = white, I thought it was the other way around and now I scan what I need with no problem

**Comment by RELNO** [comment]
@SRobles97 happy to hear this works for you and thank you for helping to debug. Please test it further and lmk if you run into issues.

**Comment by SRobles97** [comment]
![imagen](https://user-images.githubusercontent.com/37591168/212359187-c55338ab-f647-4f22-982b-a3f3a6fb94a6.png)
So I am having trouble with two patterns that are not recognized

and a tag that is recognized with the patterns the other way around
![imagen](https://user-images.githubusercontent.com/37591168/212361045-9d20ba1f-4e6d-4288-b020-75422ed5278c.png)

this is my test.json
```json
{
  "CITYIO_API_URL": "https://cityio.media.mit.edu/api/table/",
  "CITYSCOPE_PRJ_NAME": "test",
  "TOGGLE_SEND_TO_CITYIO": true,
  "nrows": 3,
  "ncols": 3,
  "cell_gap": 30,
  "camId": 0,
  "interval": 2000,
  "gui": true,
  "mirror_cam": true,
  "keystone_points_list": "446.0  59.0  216.0  44.0  431.0  283.0  206.0  273.0",
  "types": {
    "Campus": {
      "name": "Campus",
      "color": [
        171,
        143,
        57
      ],
      "height": [
        0,
        15,
        30
      ],
      "cityscopy_id": 0,
      "cityscopy_pattern": "1111111111111111"
    },
    "Oficina": {
      "name": "Oficina",
      "color": [
        36,
        130,
        198
      ],
      "height": [
        0,
        50,
        100
      ],
      "cityscopy_id": 1,
      "cityscopy_pattern": "1111111111111110"
    },
    "Parque": {
      "name": "Parque",
      "color": [
        126,
        179,
        70
      ],
      "height": [
        0,
        0,
        0
      ],
      "cityscopy_id": 2,
      "cityscopy_pattern": "1111111111111101"
    },
    "Residencial": {
      "name": "Residencial",
      "color": [
        185,
        126,
        24
      ],
      "height": [
        0,
        50,
        100
      ],
      "cityscopy_id": 3,
      "cityscopy_pattern": "1111111111111100"
    },
    "Escuela": {
      "name": "Escuela",
      "color": [
        0,
        0,
        0
      ],
      "height": [
        0,
        0,
        0
      ],
      "cityscopy_id": 1,
      "cityscopy_pattern": "0011111111111111"
    }
  }
}
```

**Comment by RELNO** [comment]
looks like you have `"cityscopy_id": 1,` twice in your settings. Can you try giving it unique ID and also (if it's not the case ey) make sure the RGB values are very distinct?

**Comment by SRobles97** [comment]
I'm still presenting problems scanning some patterns.
I have hopes that is because of the poor resolution of my webcam.
My teacher has to buy a webcam for the project anyway so I need to know if you have any recommendations on that.

**Comment by RELNO** [comment]
@SRobles97 I did not have a chance to take a look yet into other types, I'll try in the coming days. In the meantime it will be helpful to get a sense on which types work well for you and which not. You can see if the scanner found the right color based on the square inside so I don't think the camera is the issue

**Comment by SRobles97** [comment]
The types I have problems with are the ones with black cells on the corners.
This are my troubled types:
```json
    "Universidad": {
      "name": "Universidad",
      "color": [
        255,
        255,
        255
      ],
      "height": [
        0,
        5,
        0
      ],
      "cityscopy_id": 5,
      "cityscopy_pattern": "0111111111111111"
    }
    ,
    "Oficina": {
      "name": "Oficina",
      "color": [
        0,
        0,
        0
      ],
      "height": [
        0,
        3,
        0
      ],
      "cityscopy_id": 6,
      "cityscopy_pattern": "1111111111111110"
    }
    ,
    "Hospital": {
      "name": "Hospital",
      "color": [
        255,
        255,
        255
      ],
      "height": [
        0,
        8,
        0
      ],
      "cityscopy_id": 7,
      "cityscopy_pattern": "1110111111111111"
    }
    ,
    "Cementerio": {
      "name": "Cementerio",
      "color": [
        1,
        2,
        3
      ],
      "height": [
        0,
        0,
        0
      ],
      "cityscopy_id": 8,
      "cityscopy_pattern": "1111111111110111"
    }
 
```

As it is this is what is scanned
![imagen](https://user-images.githubusercontent.com/37591168/212980519-41dd2c0a-e7f0-450f-bcfb-2458b2066b0f.png)

If I change the pattern of 'Universidad' to all whites this happens
![imagen](https://user-images.githubusercontent.com/37591168/212980773-978c25d9-6e0b-464f-bfff-41646053accd.png)

And it's the same if I did for the next type and the next
![imagen](https://user-images.githubusercontent.com/37591168/212980963-8ab9ae46-9abd-44bb-8bcb-a157a0e741dc.png)

![imagen](https://user-images.githubusercontent.com/37591168/212981076-ec422010-34b0-42c0-85c6-e3c590e0b874.png)

So it recognizes only the first type as if the next have the same pattern I think

**Comment by RELNO** [comment]
you don't have a problem b/c these are actually the same type 😄 
Think of this that way: if you rotate your lego object, this is the same corner in 0, 90, 180, 270 deg. 
This is why, when you run `setup` phase, the tool creates unique tags that won't replicate in rotation. 

So - create unique tags and try again.

**Comment by RELNO** [comment]
another point: Height data format is [min, current, max]

**Comment by SRobles97** [comment]
> you don't have a problem b/c these are actually the same type smile Think of this that way: if you rotate your lego object, this is the same corner in 0, 90, 180, 270 deg. This is why, when you run `setup` phase, the tool creates unique tags that won't replicate in rotation.
> 
> So - create unique tags and try again.

I understand now
Thank you for your help

**Comment by RELNO** [comment]
Thanks and please keep on finding issues! it helps the dev. process
