### ISSUE TITLE
Enable to save Keystone settings

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#2]
Following the README instruction
`````
dhcp-18-30-26-207:tools Arno$ python3 keystone.py 
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
<VideoCapture 0x11aae4dd0>
select 4 points, by double clicking on each of them in the order: 
	up right, up left, bottom right, bottom left.
point  #  0 (588, 67)
point  #  1 (368, 67)
point  #  2 (339, 380)
point  #  3 (563, 384)
Traceback (most recent call last):
  File "keystone.py", line 133, in <module>
    np.savetxt(FILE_PATH, POINTS)
  File "/Users/Arno/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1317, in savetxt
    open(fname, 'wt').close()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Arno/Projects/GitHub/CS_Scanner_Python/scanner/tools/DATA/keystone.txt'
`````

**Comment by RELNO** [comment]
as said, readme is not up to date. Also no reason to use the initial keystone tool as a simpler way would be to run the main tool (run.py) and then key stone and save [click s]

**Comment by agrignard** [comment]
Ok. What do you mean by "as said"?

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_CityIO_Backend/issues/63#issuecomment-472044286

readme should be more up to date now, LMK if there're still issues.

**Comment by agrignard** [comment]
Ok I am kind of beta testing the doc here:

What I found could be interesting to have in the doc:

- The  4 clicks to choose the corner of the frame is pretty useful, even if I can guess that you can control it with the slider (but it's less intuitive)
 - How to control the number of cells in the grid (ncols, nrows)
- Where to define the id? for instance id=1 is white, white,white, white, id=2 is white,black,white,white

Maybe this is something that needs to be change directly in the code?

Ultimately the work done by LIMA is pretty cool in term of interface (I know it's not that straightforward to do this in python)
https://github.com/CityScope/CSL_Lima/wiki/Lego-Reader-Project

The only problem with the LIMA scan is the stability of the scanner that unfortunnately doesn't run for ever. (see https://github.com/CityScope/CSL_Lima/issues/33)

**Comment by RELNO** [comment]
yes, I guess it's sort of a trade-off. 
CityScopeJS is all about UI/UX, ease of use, etc. Also docs are more elaborated: https://github.com/CityScope/CS_cityscopeJS_Scanner

Please feel free to document the points you've mentioned [and other beta testing issues] thanks!

**Comment by RELNO** [comment]
key stone path issue resolved at https://github.com/CityScope/CS_Scanner_Python/commit/49b65d726e3ba65c710278e447f5173fcecf68a1

**Comment by agrignard** [comment]
`````
dhcp-18-30-26-207:tools Arno$ python3 keystone.py 
OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!
<VideoCapture 0x113a2cdd0>
select 4 points, by double clicking on each of them in the order: 
	up right, up left, bottom right, bottom left.
point  #  0 (876, 163)
point  #  1 (518, 134)
point  #  2 (867, 579)
point  #  3 (518, 582)
Traceback (most recent call last):
  File "keystone.py", line 132, in <module>
    np.savetxt(FILE_PATH, POINTS)
  File "/Users/Arno/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1317, in savetxt
    open(fname, 'wt').close()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Arno/Projects/GitHub/CS_Scanner_Python/scanner/tools/scanner/DATA/keystone.txt'
`````

**Comment by agrignard** [comment]
ok so if I run it from the root folder 
'''''
python scanner/tools/keystone.py
'''''
it works if i run it from the scanner/tools folder it crashes
