### ISSUE TITLE
Doubts about tags colors

### ISSUE THREAD

**Issue by SRobles97** [CityScope/CS_Scanner_Python#20]
I'm trying out the scanner and it's all good, the only trouble I have is when I'm using new colors generated by a little script I wrote that generates a random rgb and some colors are showed transparent in the CityScopeJS platform...
So are there any colors that can't be used or I'm doing something wrong?
Also, can I use hex instead of rgb?

Note: The color I tried to use was rgb(141, 170, 145)

Edit: I tried again and the color shows just fine... so the only doubt I got left is about using hex instead of rgb

**Comment by RELNO** [comment]
At this point I suggest keeping 3 values RGB colors. The CSjs tool must use them given some internal API, and hex conversion to RGB with opacity (alpha) can cause issues.

**Comment by SRobles97** [comment]
Ok I'll keep using rgb then, thank you for your answer.

**Comment by RELNO** [comment]
BTW - merged the branch into master, as it seems to work well now. Please report further issues. thanks
