### ISSUE TITLE
Keystone on the fly

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#5]
I am trying to do a keystone on the fly pressing '1,2,3,4' as mention in the documentation however nothing happens. 

Also how can I see the interface to keystone ? Maybe the interface doesn't exist anymore due to the removal of QT? 

Pressing 1,2,3,4 would be ok

**Comment by RELNO** [comment]
1,2,3,4 only select corner, WASD moves it. You should see feedback in terminal.

**Comment by agrignard** [comment]
ok sorry it moves but it's very precise so I thought it didn't work.

**Comment by RELNO** [comment]
Cool. Yes, it's pixel per click, I should implement more steps.
