### ISSUE TITLE
How to encode a lego 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#6]
I could'nt find it the documentation what is the proper order to define a type

Assuming I have this lego

![lego](https://user-images.githubusercontent.com/3928502/59374191-4c945880-8d19-11e9-96d2-064252691151.jpg)

Is it 
````
0011001111001100
````

or 

````
1100110000110011
````

I think I am missing something as I don't understand how you can have value like this for instance in deepscope

````
1110111111111111
````

or 
````
1000000000000000
````

**Comment by RELNO** [comment]
scanner look at things from up left, row by row. So for this case, it will be: 
`0011001111001100`
BUT: keep in mind your camera location. If your camera is mirrored or if you're using a mirror to enlarge the scanned area, you should do one of two: either mirror this tag (in this case it is the same) OR set a `mirror_cam` option here: https://github.com/CityScope/CS_Scanner_Python/blob/45f305dd3252b6baed3c8fc0128b7e42783004b3/cityio.json#L28
