### ISSUE TITLE
Adding "insert image" to the scanner

### ISSUE THREAD

**Issue by 88yh** [CityScope/CS_Scanner_Python#7]
I guess adding insert image feature would make the scanner usable even without a camera, a feature that would avoid the poor lighting options as well as the ability to prepare image processing using a digital software as well (ie, photoshop, gimp, krita)

**Comment by RELNO** [comment]
@88yh thanks -- can you explain how this would work? If one loads a local image, I'd imagine it would be static so that the scan only show one state.

**Comment by 88yh** [comment]
@RELNO Thanks for your response.
I suppose that if I needed to upload an image, I would not need the real time update, perhaps I would need a manual update. Which would also not be as stressful to the server.
But it also brings another thing which is video feature.

**Comment by RELNO** [comment]
I suggest to start exploring this here:  https://github.com/CityScope/CS_CityScoPy/blob/d94f6c101fd7e94d9cc2a745ec5c8859373cbb2d/cityscopy.py#L106

There could also be a simple flag on `__settings.json__` that let the class know if to expect a camera or a video/image.

**Comment by 88yh** [comment]
Thank you
