### ISSUE TITLE
Libraries Installation

### ISSUE THREAD

**Issue by 88yh** [CityScope/CS_Scanner_Python#8]
When I tried installing the scanner I noticed that it needs additional libraries installed, which could require a more user friendly to a non-developer person.
I hope that there would be a process to avoid this hassle for non-tech users.
Thanks

**Comment by RELNO** [comment]
Package installation is common practice in python. For totally non-tech alternative, an app with automated installation  should be developed (and support all OSs, different devices, etc.) 
As mentioned, a JS version exist here: https://github.com/CityScope/CS_cityscopeJS_Scanner but it lacks some of the core features of the python one.

**Comment by RELNO** [comment]
closing for now.
